---
title: "MS2"
author: "Kiera O'Brien"
date: 02/14/2020
output: html_document
---
repo link: https://github.com/kieraeobrien/MS2

The first project I looked at was Performance of Political Ads on Google, made by Michelle Gao. It utilizes the fivethirtyeight data set, which is already cleaned and packaged. A pro of this project is that it deals with a subject I'm very interested in, U.S. elections. The information it presents is also easy to understand. A con of this project is that the graphics did not appear to be very advanced relative to some of the other projects. It was also a little difficult to navigate, with the selection check boxes for candidates and multiple taps of visualizations. Additionally, the relationship it examines is well known, making the value add of the project the visual presentation rather than the conclusions drawn. 

The second project I looked at was New Zealand Wine Exploration: Growth of the New Zealand Wine Industry, made by Annabelle Paterson. The data used were pulled from two different sources, one covering statistics of wine production in New Zealand and another providing regional data for the country. A pro of this project is that it covers a niche subject that hasn't been analyzed in many studies. It also provides an interesting graphic covering distribution of New Zealand wines globally, which provides some context for the study. A con of this project is that, while interesting, the project doesn't provide information relevant outside of the exercise of creating it.  
